image: docker:latest
services:
  - docker:dind

variables:
  TAG: 'latest'

stages:
  - build
  - publish

.build: &build_template
  stage: build
  image: microsoft/dotnet:2.2-sdk-alpine
  cache:
    key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME"
    paths:
      - .nuget/
  script:
    - dotnet restore -s https://api.nuget.org/v3/index.json --packages ./.nuget/
    - dotnet publish --no-restore -c Release -o ./docker/publish/

develop_build:
  <<: *build_template
  only:
    - master
  artifacts:
    expire_in: 1 day
    paths:
      - docker/

.docker: &docker_template
  stage: publish
  script:
    - mkdir docker/app/
    - export DOCKER_HOST=$DOCKER_PORT
    - mv docker/publish/$ASSEMBLY_NAME.* docker/app/
    - mv docker/publish/*.config docker/app/
    - mv docker/publish/*.json docker/app/
    - cp Dockerfile docker/
    - docker build -t $TAG ./docker/
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $TAG

develop_docker:
  <<: *docker_template
  only:
    - master
  dependencies:
    - develop_build
  variables:
    ASSEMBLY_NAME: AliasMailApi
    TAG: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
