// <auto-generated />
using System;
using AliasMailApi.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AliasMailApi.Migrations
{
    [DbContext(typeof(MessageContext))]
    [Migration("20190816122546_AbstractBaseModelTemplate")]
    partial class AbstractBaseModelTemplate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AliasMailApi.Models.BaseMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<DateTimeOffset>("Created");

                    b.Property<DateTimeOffset?>("Deleted");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<bool>("Error");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096);

                    b.Property<string>("RemoteIpAddress")
                        .HasMaxLength(45);

                    b.Property<bool>("Valid");

                    b.Property<DateTimeOffset>("Validated");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseMessage");
                });

            modelBuilder.Entity("AliasMailApi.Models.Domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<bool>("Active");

                    b.Property<DateTimeOffset>("Created");

                    b.Property<DateTimeOffset?>("Deleted");

                    b.Property<string>("Description")
                        .HasMaxLength(2048);

                    b.Property<string>("Name")
                        .HasMaxLength(253);

                    b.HasKey("Id");

                    b.ToTable("Domains");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f49c0b55-451c-4955-a25a-a9a19f8e039f"),
                            Active = true,
                            Created = new DateTimeOffset(new DateTime(2019, 8, 16, 9, 25, 45, 879, DateTimeKind.Unspecified).AddTicks(1664), new TimeSpan(0, -3, 0, 0, 0)),
                            Description = "",
                            Name = "vinicius.sl"
                        });
                });

            modelBuilder.Entity("AliasMailApi.Models.Mail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<string>("Attachments")
                        .HasMaxLength(16384);

                    b.Property<Guid?>("BaseMessageId")
                        .HasMaxLength(36);

                    b.Property<string>("BodyHtml")
                        .HasMaxLength(10485760);

                    b.Property<string>("BodyPlain")
                        .HasMaxLength(10485760);

                    b.Property<DateTimeOffset>("Created");

                    b.Property<DateTimeOffset?>("Date");

                    b.Property<DateTimeOffset?>("Deleted");

                    b.Property<DateTimeOffset?>("ErrorDate");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096);

                    b.Property<string>("FromAddress")
                        .HasMaxLength(256);

                    b.Property<string>("FromDisplayName")
                        .HasMaxLength(256);

                    b.Property<string>("InReplyTo")
                        .HasMaxLength(4096);

                    b.Property<int>("JobStats");

                    b.Property<string>("MailAttachmentsJobErrorMessage")
                        .HasMaxLength(4096);

                    b.Property<string>("MailAttachmentsJobStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false);

                    b.Property<string>("MessageId")
                        .HasMaxLength(4096);

                    b.Property<DateTimeOffset?>("NextRetry");

                    b.Property<string>("OriginalDate")
                        .HasMaxLength(256);

                    b.Property<string>("Received")
                        .HasMaxLength(16384);

                    b.Property<string>("Recipient");

                    b.Property<string>("References")
                        .HasMaxLength(4096);

                    b.Property<int>("Retries");

                    b.Property<string>("SenderAddress")
                        .HasMaxLength(256);

                    b.Property<string>("SenderDisplayName")
                        .HasMaxLength(256);

                    b.Property<int>("Source");

                    b.Property<string>("Subject");

                    b.Property<string>("ToAddress")
                        .HasMaxLength(256);

                    b.Property<string>("ToDisplayName")
                        .HasMaxLength(256);

                    b.Property<string>("UserAgent")
                        .HasMaxLength(4096);

                    b.Property<string>("remoteIpAddress")
                        .HasMaxLength(45);

                    b.HasKey("Id");

                    b.HasIndex("BaseMessageId");

                    b.ToTable("Mails");
                });

            modelBuilder.Entity("AliasMailApi.Models.MailAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36);

                    b.Property<Guid>("MailId");

                    b.Property<string>("ContentType");

                    b.Property<DateTimeOffset>("Created");

                    b.Property<byte[]>("Data");

                    b.Property<DateTimeOffset?>("Deleted");

                    b.Property<string>("Name");

                    b.Property<long>("Size");

                    b.Property<string>("url");

                    b.HasKey("Id", "MailId");

                    b.HasAlternateKey("Id");

                    b.HasIndex("MailId");

                    b.ToTable("MailAttachments");
                });

            modelBuilder.Entity("AliasMailApi.Models.Mailbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<DateTimeOffset>("Created");

                    b.Property<bool>("CreatedManually");

                    b.Property<bool>("Delete");

                    b.Property<DateTimeOffset?>("Deleted");

                    b.Property<string>("Description")
                        .HasMaxLength(2048);

                    b.Property<Guid>("DomainId");

                    b.Property<string>("Email")
                        .HasMaxLength(512);

                    b.Property<bool>("Reject");

                    b.Property<int>("StoreQuantity");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("Mailboxes");
                });

            modelBuilder.Entity("AliasMailApi.Models.MailgunMessage", b =>
                {
                    b.HasBaseType("AliasMailApi.Models.BaseMessage");

                    b.Property<int>("AttachmentCount");

                    b.Property<string>("Attachments");

                    b.Property<string>("BodyHtml");

                    b.Property<string>("BodyPlain");

                    b.Property<string>("ContentIdMap");

                    b.Property<string>("ContentType");

                    b.Property<string>("Date");

                    b.Property<string>("From");

                    b.Property<string>("InReplyTo");

                    b.Property<string>("MessageHeaders");

                    b.Property<string>("MessageId");

                    b.Property<string>("MimeVersion");

                    b.Property<string>("Received");

                    b.Property<string>("Recipient");

                    b.Property<string>("References");

                    b.Property<string>("Sender");

                    b.Property<string>("Signature");

                    b.Property<string>("StrippedHtml");

                    b.Property<string>("StrippedSignature");

                    b.Property<string>("StrippedText");

                    b.Property<string>("Subject");

                    b.Property<string>("Timestamp");

                    b.Property<string>("To");

                    b.Property<string>("Token")
                        .HasMaxLength(50);

                    b.Property<string>("UserAgent");

                    b.Property<string>("XMailgunVariables");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("MailgunMessage");
                });

            modelBuilder.Entity("AliasMailApi.Models.Mail", b =>
                {
                    b.HasOne("AliasMailApi.Models.BaseMessage", "BaseMessage")
                        .WithMany("Mails")
                        .HasForeignKey("BaseMessageId");
                });

            modelBuilder.Entity("AliasMailApi.Models.MailAttachment", b =>
                {
                    b.HasOne("AliasMailApi.Models.Mail", "mail")
                        .WithMany("MailAttachments")
                        .HasForeignKey("MailId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AliasMailApi.Models.Mailbox", b =>
                {
                    b.HasOne("AliasMailApi.Models.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
